Custom background color support for AvatarView
OfficeDev/ui-fabric-android pull request #6
Opened 2019-08-08 12:53 UTC by EtiNegevMSFT

2019-08-08 12:53 UTC, msftclas commented
[![CLA assistant check](https://cla.opensource.microsoft.com/pull/badge/not_signed)](https://cla.opensource.microsoft.com/OfficeDev/ui-fabric-android?pullRequest=6) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/OfficeDev/ui-fabric-android?pullRequest=6) before we can accept your contribution.<br/><br/>:x: EtiNegevMSFT [sign now](https://cla.opensource.microsoft.com/OfficeDev/ui-fabric-android?pullRequest=6)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/OfficeDev/ui-fabric-android?pullRequest=6) it.</sub>

2019-08-08 20:52 UTC, lynamemi requested changes
Thank you so much for your contribution! The code looks great, and I'm impressed you found all the little places that this code change propagates to. The changes requested are small, let me know if you have other thoughts.

In the future, we love seeing screenshots of the demo app changes in the description, but no need to worry about it this time.

2019-08-08 20:52 UTC, lynamemi commented on OfficeUIFabric.Demo/src/main/res/layout/activity_avatar_view.xml
> +                app:backgroundColor="@android:color/holo_blue_bright"/>
Could you sub this out for one of the "dark" holo colors? The white on bright background isn't looking very accessible.

2019-08-08 20:52 UTC, lynamemi commented on OfficeUIFabric.Demo/src/main/java/com/microsoft/officeuifabricdemo/demos/AvatarViewActivity.kt
> +        avatar_example_xsmall_initials.backgroundColor = Color.RED
Not that the xsmall avatar is easy to ready anyway... But could you make this one a bit darker for accessibility too?  Maybe `DKGRAY` or something custom?

2019-08-08 20:52 UTC, lynamemi commented on OfficeUIFabric/src/main/java/com/microsoft/officeuifabric/persona/AvatarView.kt
> +    var backgroundColor: Int? = null
Let's name this `avatarBackgroundColor` since it ultimately gets propagated to `PersonaView` as well.

2019-08-08 20:52 UTC, lynamemi commented on OfficeUIFabric/src/main/java/com/microsoft/officeuifabric/persona/AvatarView.kt
> +    var backgroundColor: Int? = null
And can you move it below the `avatarImageUri` property? Just want the image setting properties to have more priority. You have it in that location in other places, too.

2019-08-08 20:52 UTC, lynamemi commented on OfficeUIFabric/src/main/java/com/microsoft/officeuifabric/persona/AvatarView.kt
> +    backgroundColor = avatar.backgroundColor
And then can you move this one down to the bottom, too?

2019-08-08 20:52 UTC, lynamemi commented on OfficeUIFabric/src/main/java/com/microsoft/officeuifabric/persona/IAvatar.kt
> +    var backgroundColor: Int?
=> avatarBackgroundColor

2019-08-08 20:52 UTC, lynamemi commented on OfficeUIFabric/src/main/res/values/attrs_avatar.xml
> +        <attr name="backgroundColor" format="reference" />
=> avatarBackgroundColor

2019-08-08 20:52 UTC, lynamemi commented on OfficeUIFabric/src/main/java/com/microsoft/officeuifabric/persona/InitialsDrawable.kt
> +    fun setInfo(name: String, email: String, @ColorInt colorInt: Int? = null) {
colorInt => customBackgroundColor ?

2019-08-09 18:28 UTC, vladfilyakov commented on OfficeUIFabric.Demo/src/main/java/com/microsoft/officeuifabricdemo/util/PersonaUtils.kt
> +    override var backgroundColor: Int? = null
=> avatarBackgroundColor

2019-08-09 18:33 UTC, vladfilyakov commented on OfficeUIFabric/src/main/java/com/microsoft/officeuifabric/persona/IPersona.kt
> +    override var backgroundColor: Int? = null
=> avatarBackgroundColor

2019-08-12 15:39 UTC, lynamemi approved these changes

2019-08-12 16:19 UTC, lynamemi commented
/AzurePipelines run

2019-08-12 16:43 UTC, vladfilyakov commented
/AzurePipelines run

2019-08-12 17:29 UTC, lynamemi commented
@EtiNegevMSFT there's nothing wrong with the build on your end - It appears that there is a GitHub + AzureDevops integration issue we need to fix so stay tuned.

2019-08-12 17:47 UTC, vladfilyakov commented
/azp run

2019-08-12 17:57 UTC, merged